#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Fondo de pantalla
feh --bg-fill ~/Imágenes/wallpaper/wall-01.png &

# Resolucion de monitor
xrandr --output Virtual-1 --mode 1920x1080 --rate 60 &

# Ruta de la polybar
~/.config/polybar/launch.sh &

# Picom
picom --config ~/.config/picom/picom.conf &

# Flameshot
flameshot &
